import {
  Armchair,
  BadgePercent,
  Building2,
CalendarClock,
  ChartColumn,
  CircleUser,
  Clapperboard,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  DoorOpen,
  FolderOpen,
  Image as ImageIcon,
  Images,
  Inbox,
  Star,
  Settings,
  Tag,
  Ticket,
  TrendingUp,
  Users,
  UsersRound,
  Wrench,
} from "lucide-react";

export const adminNavSections = [
  {
    label: "Overview",
    labelKey: "admin.overview",
    icon: Compass,
    items: [
      {
        name: "Dashboard",
        nameKey: "admin.dashboard",
        icon: ChartColumn,
        path: "/admin/dashboard",
      },
      {
        name: "Analytics",
        nameKey: "admin.analytics",
        icon: TrendingUp,
        path: "/admin/analytics",
      },
      {
        name: "Reports",
        nameKey: "admin.reports",
        icon: ClipboardList,
        path: "/admin/reports",
      },
    ],
  },
  {
    label: "Management",
    labelKey: "admin.management",
    icon: FolderOpen,
    items: [
      {
        name: "Movies",
        nameKey: "admin.movies",
        icon: Clapperboard,
        path: "/admin/movies",
      },
      {
        name: "Coming Soon",
        nameKey: "admin.comingSoon",
        icon: CalendarClock,
        path: "/admin/coming-soon",
      },
      {
        name: "Cinemas",
        nameKey: "admin.cinemas",
        icon: Building2,
        path: "/admin/cinemas",
      },
      {
        name: "Rooms",
        nameKey: "admin.rooms",
        icon: DoorOpen,
        path: "/admin/rooms",
      },
      {
        name: "Seats",
        nameKey: "admin.seats",
        icon: Armchair,
        path: "/admin/seats",
      },
      {
        name: "Showtimes",
        nameKey: "admin.showtimes",
        icon: Clock,
        path: "/admin/showtimes",
      },
      {
        name: "Categories",
        nameKey: "admin.categories",
        icon: Tag,
        path: "/admin/categories",
      },
      {
        name: "Team Members",
        nameKey: "admin.team",
        icon: UsersRound,
        path: "/admin/team",
      },
      {
        name: "Discounts",
        nameKey: "admin.discounts",
        icon: BadgePercent,
        path: "/admin/discounts",
      },
      {
        name: "Gallery",
        nameKey: "admin.gallery",
        icon: Images,
        path: "/admin/gallery",
      },
    ],
  },
  {
    label: "Operations",
    labelKey: "admin.operations",
    icon: Settings,
    items: [
      {
        name: "Bookings",
        nameKey: "admin.bookings",
        icon: Ticket,
        path: "/admin/bookings",
      },
      {
        name: "Payments",
        nameKey: "admin.payments",
        icon: CreditCard,
        path: "/admin/payments",
      },
      {
        name: "Reviews",
        nameKey: "admin.reviews",
        icon: Star,
        path: "/admin/reviews",
      },
      {
        name: "Messages",
        nameKey: "admin.messages",
        icon: Inbox,
        path: "/admin/contacts",
      },
    ],
  },
  {
    label: "Settings",
    labelKey: "admin.settings",
    icon: Wrench,
    items: [
      {
        name: "Users",
        nameKey: "admin.users",
        icon: Users,
        path: "/admin/users",
      },
      {
        name: "Hero Images",
        nameKey: "admin.heroImages",
        icon: ImageIcon,
        path: "/admin/heroes",
      },
      {
        name: "Profile",
        nameKey: "admin.myProfile",
        icon: CircleUser,
        path: "/admin/profile",
      },
    ],
  },
];