<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MovieSeeder extends Seeder
{
    public function run(): void
    {
        $movies = [
    [
            'category' => 'Action',
            'title' => 'John Wick: Chapter 4',
            'description' => 'With the price on his head ever increasing, legendary hit man John Wick takes his fight against the High Table global as he seeks out the most powerful players in the underworld.',
            'duration' => 169,
            'release_date' => '2025-03-24',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789742132/cinema/movies/posters/jmnb2fyfi1xu6ix3gr5w.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=qEvGmOUQyZM',
            'rating' => '8.0',
            'status' => 'active',
        ],
    [
            'category' => 'Action',
            'title' => 'Deadpool & Wolverine',
            'description' => 'A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary Deadpool behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit up with an even more reluctant Wolverine.',
            'duration' => 128,
            'release_date' => '2025-07-26',
            'poster' => 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=73_1biulkYk',
            'rating' => '8.1',
            'status' => 'active',
        ],
    [
            'category' => 'Horror',
            'title' => 'គាស់ផ្នូរ',
            'description' => 'Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving a mysterious entity as they face their most dangerous challenge.',
            'duration' => 112,
            'release_date' => '2025-09-05',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789702663/cinema/movies/posters/rhuvmrgvqp6acfxefffw.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=YBYXEXx6wao',
            'rating' => '7.5',
            'status' => 'active',
        ],
    [
            'category' => 'Action',
            'title' => 'Bad Boys: Ride or Die',
            'description' => 'When their late police captain gets framed, Miami\'s best cops must go on the run to clear his name, uncovering a vast conspiracy in the process.',
            'duration' => 115,
            'release_date' => '2025-06-07',
            'poster' => 'https://image.tmdb.org/t/p/w500/oGythE98MYleE6mZlGs5oBGkux1.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=leEeUfM00Z8',
            'rating' => '7.0',
            'status' => 'active',
        ],
    [
            'category' => 'Action',
            'title' => 'Furiosa: A Mad Max Saga',
            'description' => 'The origin story of the renegade young Furiosa before she teamed up with Mad Max in the post-apocalyptic Wasteland.',
            'duration' => 148,
            'release_date' => '2025-05-24',
            'poster' => 'https://image.tmdb.org/t/p/w500/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=XJMuhwVlca4',
            'rating' => '7.9',
            'status' => 'active',
        ],
    [
            'category' => 'Action',
            'title' => 'Avengers: Endgame',
            'description' => 'After the devastating events of Infinity War, the Avengers assemble once more to reverse Thanos\' actions and restore balance to the universe.',
            'duration' => 181,
            'release_date' => '2025-04-26',
            'poster' => 'https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
            'rating' => '8.4',
            'status' => 'active',
        ],
    [
            'category' => 'Action',
            'title' => 'Spider-Man: No Way Home',
            'description' => 'With Spider-Man\'s identity revealed, Peter Parker asks Doctor Strange for help, but a botched spell tears open the multiverse and brings in deadly foes from every reality.',
            'duration' => 148,
            'release_date' => '2025-12-17',
            'poster' => 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=JfVOs4VSpmA',
            'rating' => '8.2',
            'status' => 'active',
        ],
    [
            'category' => 'Comedy',
            'title' => 'Free Guy',
            'description' => 'A bank teller stuck in his routine discovers he is actually a background player in an open-world video game and decides to become the hero of his own story.',
            'duration' => 115,
            'release_date' => '2025-08-13',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789749796/cinema/movies/posters/eigletlbb5gy7cxa5zbt.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=X2m-08cOAbc',
            'rating' => '7.1',
            'status' => 'active',
        ],
    [
            'category' => 'Horror',
            'title' => 'The Conjuring',
            'description' => 'Paranormal investigators Ed and Lorraine Warren help a family terrorized by a dark presence in their secluded farmhouse.',
            'duration' => 112,
            'release_date' => '2025-07-19',
            'poster' => 'https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=k10ETZ41q5o',
            'rating' => '7.5',
            'status' => 'active',
        ],
    [
            'category' => 'Romance',
            'title' => 'Titanic',
            'description' => 'A young aristocrat falls in love with a penniless artist aboard the ill-fated maiden voyage of the RMS Titanic.',
            'duration' => 195,
            'release_date' => '2025-12-19',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789749965/cinema/movies/posters/teocghnauejpx8zrydhq.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=2e-eXJ6HgkQ',
            'rating' => '7.9',
            'status' => 'active',
        ],
    [
            'category' => 'Animation',
            'title' => 'Inside Out',
            'description' => 'After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions guide her through the challenges of a new city, house, and school.',
            'duration' => 95,
            'release_date' => '2025-06-19',
            'poster' => 'https://image.tmdb.org/t/p/w500/j91LJmcWo16CArFOoapsz84bwxb.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=yRUAzGQ3nSY',
            'rating' => '8.1',
            'status' => 'active',
        ],
    [
            'category' => 'Science Fiction',
            'title' => 'Interstellar',
            'description' => 'When Earth becomes uninhabitable, a former NASA pilot leads a mission through a wormhole in search of a new home for humanity.',
            'duration' => 169,
            'release_date' => '2025-11-07',
            'poster' => 'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=zSWdZVtXT7E',
            'rating' => '8.7',
            'status' => 'active',
        ],
    [
            'category' => 'Science Fiction',
            'title' => 'Avatar',
            'description' => 'A paraplegic Marine dispatched to the moon Pandora becomes torn between following his orders and protecting the world he has come to call home.',
            'duration' => 162,
            'release_date' => '2025-12-18',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789749763/cinema/movies/posters/khnwmspqvnyajte0mkie.jpg',
            'trailer_url' => 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
            'rating' => '8.0',
            'status' => 'active',
        ],
    [
            'category' => 'Fantasy',
            'title' => 'Age of Wonders',
            'description' => 'In a realm where magic is fading, a young mage must rally the scattered kingdoms and uncover an ancient artifact before the world falls into eternal shadow.',
            'duration' => 140,
            'release_date' => '2026-10-02',
            'poster' => 'https://upload.wikimedia.org/wikipedia/en/e/e5/Aowboxart.jpg',
            'trailer_url' => NULL,
            'rating' => '7.8',
            'status' => 'coming soon',
        ],
    [
            'category' => 'Action',
            'title' => 'Crimson Tide',
            'description' => 'A tense submarine thriller where the crew of a nuclear sub faces a near-total breakdown of command, with the fate of the world hanging in the balance.',
            'duration' => 115,
            'release_date' => '2026-10-09',
            'poster' => 'https://m.media-amazon.com/images/M/MV5BNTNhZDk2NmQtNDc3ZC00Nzk3LWFmNTctYTc0OWMyNGM0ZWYyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg',
            'trailer_url' => NULL,
            'rating' => '8.1',
            'status' => 'coming soon',
        ],
    [
            'category' => 'Drama',
            'title' => 'Paper Moon',
            'description' => 'A Depression-era con man finds himself reluctantly traveling across the Midwest with a precocious young girl who may or may not be his daughter.',
            'duration' => 107,
            'release_date' => '2026-10-16',
            'poster' => 'https://upload.wikimedia.org/wikipedia/en/7/71/Paper-moon_small.jpg',
            'trailer_url' => NULL,
            'rating' => '8.2',
            'status' => 'coming soon',
        ],
    [
            'category' => 'Science Fiction',
            'title' => 'The Far Horizon',
            'description' => 'A crew of deep-space explorers discovers a signal from beyond the known universe and must decide whether it is a promise of salvation or a trap.',
            'duration' => 132,
            'release_date' => '2026-10-23',
            'poster' => 'https://res.cloudinary.com/t1size47/image/upload/v1789742276/cinema/movies/posters/ub1vgqgzud0pfuegq9qa.jpg',
            'trailer_url' => NULL,
            'rating' => '7.6',
            'status' => 'coming soon',
        ],
        ];

        foreach ($movies as $movie) {
            $categoryId = DB::table('movie_categories')->where('name', $movie['category'])->value('id');

            DB::table('movies')->updateOrInsert(
                ['title' => $movie['title']],
                [
                    'movie_category_id' => $categoryId,
                    'description' => $movie['description'],
                    'duration' => $movie['duration'],
                    'release_date' => $movie['release_date'],
                    'poster' => $movie['poster'],
                    'trailer_url' => $movie['trailer_url'],
                    'rating' => $movie['rating'],
                    'status' => $movie['status'],
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }
    }
}
